import { acceptHMRUpdate, defineStore } from 'pinia';

export const useSampleBlogsStore = defineStore('sampleBlogs', {
  state: () => [
    {
      id: 1,
      cards: '3',
      feature: 'right ',
      row: [
        {
          id: 1 - 1,
          span: 'col-span-3',
          tag: 'Luxury',
          img: 'https://picsum.photos/300/?random=2',
          height: 290,
          title: 'From Surging Recovery to Elegant Advance: The Evolving Future of Luxury',
          desc: 'Our 2021 Luxury Goods Worldwide Market Study shows how brands :can build on their historic rebound.',
          type: 'Report',
          date: 'Jan 04, 2022',
        },
        {
          id: 1 - 2,
          span: 'col-span-3',
          tag: 'Energy & Natural Resources',
          img: 'https://picsum.photos/300/?random=3',
          height: 290,
          title: 'Beyond COP26: An Action Plan for CEOs',
          desc: 'As measures to tackle climate change accelerate, more companies will approach their own carbon transitions with the same results orientation as any other strategic transformation.',
          type: 'Breif',
          date: 'Jan 04, 2022',
        },
        {
          id: 1 - 3,
          span: 'col-span-6',
          tag: 'Techonology',
          img: 'https://picsum.photos/400/?random=4',
          height: 350,
          title: 'Engineering Your Way Out of the Global Chip Shortage',
          desc: "If you design for resilience, you'll be better able to navigate disruptions.",
          type: 'HBR.org',
          date: 'Jan 04, 2022',
        },
      ],
    },
    {
      id: 2,
      cards: '4 ',
      feature: '',
      row: [
        {
          id: 2 - 1,
          span: 'col-span-3',
          tag: 'Technology',
          img: 'https://picsum.photos/300/?random=5',
          height: 200,
          title: 'Engineering Your Way Out of the Global Chip Shortage',
          desc: 'If you design for resilience, you’ll be better able to navigate disruptions.',
          type: 'HBR.org',
          date: 'Dec 23, 2021',
        },
        {
          id: 2 - 2,
          span: 'col-span-3',
          tag: 'Retail',
          img: 'https://picsum.photos/300/?random=6',
          height: 200,
          title: 'Happy Holidays Are In-Store for Retailers',
          desc: 'With shoppers making fewer, more purposeful trips to stores this season, every visit counts.',
          type: 'Retail Holiday Newsletter',
          date: 'Dec 20, 2021',
        },
        {
          id: 2 - 3,
          span: 'col-span-3',
          tag: 'Financial Services',
          img: 'https://picsum.photos/300/?random=7',
          height: 200,
          title: 'AI Strategy in Banking: Choose Your Spots ',
          desc: 'Done right, artificial intelligence goes beyond cost reduction to generate value for customers and reduce risk.',
          type: 'Snap Chart',
          date: 'Dec 16, 2021',
        },
        {
          id: 2 - 4,
          span: 'col-span-3',
          tag: 'Private Equity',
          img: 'https://picsum.photos/300/?random=8',
          height: 200,
          title: 'When Investors Eat the World of Fintech',
          desc: 'The worlds of fintech and financial services are merging into one.',
          type: 'The Private Equity Podcast',
          date: 'Dec 16, 2021',
        },
      ],
    },
    {
      id: 3,
      cards: '4 ',
      feature: '',
      row: [
        {
          id: 3 - 1,
          span: 'col-span-3',
          tag: 'Retail',
          img: 'https://picsum.photos/200/?random=9',
          height: 200,
          title: 'Luxury Rebound: Taking Command of the E-commerce Marketplace',
          desc: "Bain Partner Claudia D'Arpizio appeared on Bloomberg News to discuss the increase of personal luxury goods spending in 2021.",
          type: 'Video',
          date: 'Dec 15, 2021',
        },
        {
          id: 3 - 2,
          span: 'col-span-3',
          tag: 'Organization',
          img: 'https://picsum.photos/200/?random=10',
          height: 200,
          title: 'Manufacturers Have Plenty of Jobs, but Few Takers',
          desc: 'Leading companies are rapidly rethinking workforce strategies and boosting investment in automation.',
          type: 'Brief',
          date: 'Dec 15, 2021',
        },
        {
          id: 3 - 3,
          span: 'col-span-3',
          tag: 'Consumer Products',
          img: 'https://picsum.photos/200/?random=11',
          height: 200,
          title: 'A Sudden Slowdown in 2021’s FMCG Recovery … and the Mixed Fate of China’s Insurgent Brands',
          desc: 'China Shopper Report 2021, Volume 2',
          type: 'Report',
          date: 'Dec 14, 2021',
        },
        {
          id: 3 - 4,
          span: 'col-span-3',
          tag: 'Financial Services',
          img: 'https://picsum.photos/200/?random=12',
          height: 200,
          title: 'Voting with Their Feet: Banking Consumers Want a Seamless Digital Experience',
          desc: 'Half of consumers’ digital purchases go to a competitor of their primary bank, and half of those who buy anywhere encounter friction in the process. ',
          type: 'Infographic',
          date: 'Dec 14, 2021',
        },
      ],
    },
    {
      id: 4,
      cards: '2 ',
      feature: '',
      row: [
        {
          id: 4 - 1,
          span: 'col-span-6',
          tag: 'Financial Services',
          img: 'https://picsum.photos/400/?random=13',
          height: 350,
          title: 'Banks’ Missing Data Champion: The CFO',
          desc: 'The finance group is well positioned to break down silos and, alongside the CDO, help business units and IT prioritize use cases.',
          type: 'Brief',
          date: 'Dec 13, 2021',
        },
        {
          id: 4 - 2,
          span: 'col-span-6',
          tag: 'Private Equity',
          img: 'https://picsum.photos/400/?random=14',
          height: 350,
          title: 'When Software Eats the World of Finance',
          desc: 'The worlds of fintech and financial services are merging into one.',
          type: 'Dry Powder: The Private Equity Podcast',
          date: 'Dec 9, 2021',
        },
      ],
    },
    {
      id: 5,
      cards: '4 ',
      feature: '',
      row: [
        {
          id: 5 - 1,
          span: 'col-span-3',
          tag: 'Utilities & Renewables',
          img: 'https://picsum.photos/200/?random=15',
          height: 200,
          title: 'North America’s Role in Leading the Energy Transition',
          desc: 'At the Reuters North American Energy Transition Conference, Bain’s Peter Parry and Aaron Denman discuss why the region is uniquely positioned to lead the way to a lower-carbon future. ',
          type: 'Video',
          date: 'Dec 8, 2021',
        },
        {
          id: 5 - 2,
          span: 'col-span-3',
          tag: 'Healthcare',
          img: 'https://picsum.photos/200/?random=16',
          height: 200,
          title: 'Developing Digital Clinical Trials',
          desc: 'First-mover pharmaceutical companies will use digital tools to accelerate speed to market. ',
          type: 'Inforgraphic',
          date: 'Dec 7, 2021',
        },
        {
          id: 5 - 3,
          span: 'col-span-3',
          tag: 'Healthcare',
          img: 'https://picsum.photos/200/?random=17',
          height: 200,
          title: 'Pricing Relief, Stat!',
          desc: ' Inflationary times give medical technology suppliers an opening for smarter pricing.',
          type: 'Inforgraphic',
          date: 'Dec 3, 2021',
        },
        {
          id: 5 - 4,
          span: 'col-span-3',
          tag: 'Retail',
          img: 'https://picsum.photos/200/?random=18',
          height: 200,
          title: 'After Another Big Year, Online Luxury Sales Approach a Milestone',
          desc: 'Websites and apps are on track to become the most important channel for personal luxury goods.',
          type: 'Snap Chart',
          date: 'Dec 2, 2021',
        },
      ],
    },
    {
      id: 6,
      cards: '3 ',
      feature: 'left ',
      row: [
        {
          id: 6 - 1,
          span: 'col-span-6',
          tag: 'Energy & Natural Resources',
          img: 'https://picsum.photos/400/?random=19',
          height: 350,
          title: 'Helping Farmers Shift to Regenerative Agriculture ',
          desc: 'Sustainable farming techniques, such as cover crops, nutrient management, crop rotation, and low tillage, could reduce emissions by more than half. ',
          type: 'Brief',
          date: 'Dec 02, 2021',
        },
        {
          id: 6 - 2,
          span: 'col-span-3',
          tag: 'Vector℠',
          img: 'https://picsum.photos/300/?random=20',
          height: 290,
          title: 'Enterprise Technology Leaders Are More Likely to Value Diversity ',
          desc: 'Companies that value diversity are more likely to identify as leaders in technology capabilities, innovation, and customer experience. ',
          type: 'Snap Chart',
          date: 'Dec 01, 2021',
        },
        {
          id: 6 - 3,
          span: 'col-span-3',
          tag: 'Diversity, Equity & Inclusion',
          img: 'https://picsum.photos/300/?random=21',
          height: 290,
          title: 'What Works in DEI? Four Efforts Worth Measuring ',
          desc: 'Many actions can advance diversity, equity, and inclusion, but organizations often lack data to know how well they’re working. Here’s where they can do better.',
          type: 'Article',
          date: 'Nov 30, 2021',
        },
      ],
    },
  ],
});

if (import.meta.hot) {
  import.meta.hot.accept(acceptHMRUpdate(useSampleBlogsStore, import.meta.hot));
}
